@startuml "Update details (not contacts) of the existing HRManager of the existing vacancy sequence diagram"
skinparam topurl https://github.com/dimonar2186/jobHunter/tree/master/srs/algorithms/
skinparam sequenceReferenceBackgroundColor yellow

    actor "user" as user
    participant "applicationFront" as front
    participant "applicationBack" as back
    database "database" as db
    entity "HRManager" as HRManager

    user -> front : initiate update of the HRManager
    front --> user : request for HRManager's details

    loop
        user -> front : provide HRManager's details
        front -> front : check if the HRManager.name\nand contact are provided
        opt 
            front --> front : applicationStage.name is missed
            front --> user : notify\n"Provide: HRManager.name"
        end
        break
            front --> front : HRManager.name and contact\nare provided
        end
    end

    front -> back : PATCH ../user/HRManagers/{HRManagerId}
    back -> db : update the HRManager
    db -> HRManager : update
    db --> back : result
    alt "HRManager is not found"
        break
            back --> front : HTTP code 404
            front --> user : notify "The HRManager was not found"
        end
    else "HRManager update failed"
        break
            back --> front : HTTP code 504
            front --> user : notify "Error occured"
        end
    else "HRManager update is successful"
        back --> front : HTTP code 200 \nHRManager details
        front -> front : update vacancyPage
        front --> user : notify "HRManager was created"
    end

@enduml