@startuml "Delete the existing offer from the existing vacancy sequence diagram"
skinparam topurl https://github.com/dimonar2186/jobHunter/tree/master/srs/algorithms/
skinparam sequenceReferenceBackgroundColor yellow

    actor "user" as user
    participant "applicationFront" as front
    participant "applicationBack" as back
    database "database" as db
    entity "offer" as offer

    user -> front : initiate a deletion of the offer\nfrom the existing vacancy
    front -> user : request confirmation
    opt "deletion cancelled"
        user --> front : refuse
        break
        end
    end
    user --> front : confirm
    front -> back : PATCH ../user/vacancies/{vacancyId}
    back -> back : check if all offers are contained\nin the requestBody
    back -> db : delete the offer
    db -> offer !! : delete
    db --> back : result
    alt "Offer was not found"
        break
            back --> front : HTTP code 404
            front --> user : notify "The offer was not found"
        end
    else "Offer deletion failed"
        break
            back --> front : HTTP code 504
            front --> user : notify "Error occured"
        end
    else "Offer is deleted"
        back --> front : HTTP code 204 \nvacancy details
        front -> front : update vacancyPage
        front --> user : notify "Offer was deleted"
    end

@enduml